"""Pydantic schemas for the Story entity.

Separates concerns into:
  - StoryBase: shared fields between create and read
  - StoryCreate: fields required when creating a new story
  - StoryUpdate: optional fields for partial updates
  - StoryInDB: full representation as stored in Supabase (includes id, timestamps, URLs)
  - StoryBrief: lightweight projection for list/grid views
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field


class StoryBase(BaseModel):
    """Common fields shared by create and read operations."""

    speaker_name: str = Field(..., min_length=1, max_length=200, description="Name of the storyteller.")
    speaker_age: int | None = Field(default=None, ge=1, le=150, description="Age of the storyteller.")
    occupation: str | None = Field(default=None, max_length=200, description="Occupation or craft of the storyteller.")
    village: str | None = Field(default=None, max_length=200, description="Village of origin.")
    district: str = Field(..., min_length=1, max_length=200, description="District where the story was recorded.")
    state: str = Field(default="West Bengal", max_length=100, description="State where the story was recorded.")
    country: str = Field(default="India", max_length=100, description="Country where the story was recorded.")
    language: str = Field(..., min_length=1, max_length=50, description="Primary language of the recording.")


class StoryCreate(StoryBase):
    """Schema for creating a new story record.

    Audio and image URLs are set after file upload, not by the client directly.
    AI-generated fields (transcript, summary, translations, tags) are populated
    in Phase 03 — they default to None here so the record can be created
    immediately after upload.
    """

    title: str | None = Field(default=None, max_length=500, description="Title (can be auto-generated by AI later).")
    transcript: str | None = Field(default=None, description="Full transcript of the audio.")
    summary: str | None = Field(default=None, description="AI-generated summary.")
    translation_en: str | None = Field(default=None, description="English translation.")
    translation_bn: str | None = Field(default=None, description="Bengali translation.")
    translation_hi: str | None = Field(default=None, description="Hindi translation.")
    keywords: list[str] = Field(default_factory=list, description="Extracted keywords.")
    cultural_tags: list[str] = Field(default_factory=list, description="Cultural / thematic tags.")
    historical_importance: str | None = Field(default=None, description="Historical significance note.")


class StoryUpdate(BaseModel):
    """Schema for partial story updates.

    Every field is optional so callers can send only what changed.
    """

    speaker_name: str | None = Field(default=None, min_length=1, max_length=200)
    speaker_age: int | None = Field(default=None, ge=1, le=150)
    occupation: str | None = Field(default=None, max_length=200)
    village: str | None = Field(default=None, max_length=200)
    district: str | None = Field(default=None, min_length=1, max_length=200)
    state: str | None = Field(default=None, max_length=100)
    country: str | None = Field(default=None, max_length=100)
    language: str | None = Field(default=None, min_length=1, max_length=50)
    title: str | None = Field(default=None, max_length=500)
    transcript: str | None = Field(default=None)
    summary: str | None = Field(default=None)
    translation_en: str | None = Field(default=None)
    translation_bn: str | None = Field(default=None)
    translation_hi: str | None = Field(default=None)
    keywords: list[str] | None = Field(default=None)
    cultural_tags: list[str] | None = Field(default=None)
    historical_importance: str | None = Field(default=None)
    audio_url: str | None = Field(default=None)
    image_url: str | None = Field(default=None)


class StoryInDB(StoryBase):
    """Full story representation as returned from the database."""

    id: UUID
    title: str | None = None
    transcript: str | None = None
    summary: str | None = None
    translation_en: str | None = None
    translation_bn: str | None = None
    translation_hi: str | None = None
    keywords: list[str] = Field(default_factory=list)
    cultural_tags: list[str] = Field(default_factory=list)
    historical_importance: str | None = None
    audio_url: str | None = None
    image_url: str | None = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class StoryBrief(BaseModel):
    """Lightweight projection for list views and story cards."""

    id: UUID
    title: str | None = None
    speaker_name: str
    village: str | None = None
    district: str
    language: str
    image_url: str | None = None
    created_at: datetime

    model_config = {"from_attributes": True}
